### ISSUE TITLE
Problem with complex root

### ISSUE THREAD

**Issue by borneq** [yairchu/quartic#2]
Very nice - 70 thousands corrected values, but after this is:
(0 + 1*i)*x^4 + (2 + 1.5*i)*x^3 + (1.75 - 1.25*i)*x^2 + (1.5 - 0.5*i)*x + (-0.25 - 0.75*i)
should be : 
x = 0.13238882193634446795 + 0.41196389171526531629*i
x = 0.54683253027894678099 + 1.0478312184142241163*i
x = -1.8148283208115054244 + 1.1587422931938323570*i
x = -0.36439303140336444356 - 0.61853740332254218924*i
but are:
-0.68980357755814148 -0.89381445717872954 i
0.16980355368891228 + 0.53381447167331397 i
-0.68980354003499600 -0.89381448502466365 i
0.16980356390422560 + 0.53381447053008024

**Note**:   root 0 = root 2 and root 1 = root 3; how correct this?
What is sense
```cpp
for (i = 0; i <= degree; ++i)
            rev_poly[i] = poly[degree - i];
```
Without above code (when commented):
is error:
(-0.500000+-0.750000i)x^4+(1.500000-1.000000i)x^3+(-1.500000-0.250000i)x^2+(1.000000-2.000000i)x+(1.750000+1.500000)
x[0] = (-0.260532,-1.681016)
x[1] = (-0.260532,-1.681016)
x[2] = (-0.260532,-1.681016)
x[3] = (-0.260532,-1.681016)
4x the same root
Should be 
x = 0.85943419315977036206 - 0.77412781353060626644*i
x = 0.45338763457223624440 + 1.3769356875637398736*i
x = -0.85943419316042049636 - 0.22587218646880924734*i
x = -0.45338763457157105281 - 2.3769356875671676745*i

**Comment by yairchu** [comment]
Thanks for the report!

So far I noticed that the Haskell implementation `quartic.hs` solves it fine so it should be relatively easy to investigate the differences. Will update.

**Comment by yairchu** [comment]
For this case, removing the whole if block of

    if (degree > 2 && stableness_score(poly[degree], poly[degree - 1]) > stableness_score(poly[0], poly[1])) {
        ...
    }

Makes it yield the correct result. Will investigate further.

**Comment by yairchu** [comment]
Ok, so `solve_depressed_quartic` gets these results for a `helper_cubic`:

    -4.44089e-16+6.66134e-16i
    -2.0032-0.915338i
    -2.5968-4.28466i

And then just uses the first of those - which would obviously yield less numerically stable results than the other ones.

**Comment by yairchu** [comment]
Thanks for the report! I pushed a fix for this situation. Can you verify that it works for you?

Btw, I've also created an issue to add automated tests for the C implementation - https://github.com/yairchu/quartic/issues/3

**Comment by yairchu** [comment]
Closing as it is fixed. Thank for the report!
